modLoader="javafml"
loaderVersion="[36,)"
license="ISC License (ISCL) Microsoft Public License (Ms-PL)"

[[mods]]
modId="dxd_project"
version="0.0.0.0.0.2.3"
displayName="DXD Project"
credits="(пока пусто)"
displayURL="https://github.com/InkVak0485Prog/dxd-project-isc"
authors="InkVak0485, VaxerGame54, MCreator"
description='''
Демоны Старшей Школы
'''

[[dependencies.dxd_project]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




